---
gems:
- name: rails
  version: 2.0.2
- name: cgi_multipart_eof_fix
  version: 2.5.0
- name: daemons
  version: 1.0.10
- name: fit
  version: 1.1
- name: fitnesse-ruby
  version: 0.1.0
- name: has_finder
  version: 0.1.5
- name: hpricot
  version: 0.6.0
- name: json
  version: 1.1.2
- name: mime-types
  version: "1.15"
- name: rake
  version: 0.8.1
- name: rr
  version: 0.4.8
- name: Selenium
  version: 1.0.9
- name: sqlite3-ruby
  version: 1.2.1
- name: thin
  version: 0.8.1
- name: webrat
  version: 0.2.0
